version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.5.3

    working_directory: ~/repo

    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo
            
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code:
          filters:
            branches:
              ignore:
                - gh-pages